#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("CiuchApp.Mobile.Resource", IsApplication=true)]

namespace CiuchApp.Mobile
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f050003
			public const int colorAccent = 2131034115;
			
			// aapt resource value: 0x7f050001
			public const int colorPrimary = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int colorPrimaryDark = 2131034114;
			
			// aapt resource value: 0x7f050000
			public const int launcher_background = 2131034112;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int answear = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int splash = 2130837505;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f09000a
			public const int CityTextView = 2131296266;
			
			// aapt resource value: 0x7f090009
			public const int CountryTextView = 2131296265;
			
			// aapt resource value: 0x7f09000b
			public const int DatesTextView = 2131296267;
			
			// aapt resource value: 0x7f090022
			public const int PieceBuyPriceText = 2131296290;
			
			// aapt resource value: 0x7f090026
			public const int PieceEstimatedDateOfShipmentDate = 2131296294;
			
			// aapt resource value: 0x7f090027
			public const int PieceEstimatedTimeOfDeliveryDate = 2131296295;
			
			// aapt resource value: 0x7f09001a
			public const int PieceImage = 2131296282;
			
			// aapt resource value: 0x7f09001b
			public const int PieceNameText = 2131296283;
			
			// aapt resource value: 0x7f090025
			public const int PieceOrderDate = 2131296293;
			
			// aapt resource value: 0x7f090008
			public const int backSizeAmount = 2131296264;
			
			// aapt resource value: 0x7f090003
			public const int businessTripTextInfo = 2131296259;
			
			// aapt resource value: 0x7f090002
			public const int businessTripsListView = 2131296258;
			
			// aapt resource value: 0x7f09000f
			public const int citySpinner = 2131296271;
			
			// aapt resource value: 0x7f09000d
			public const int countrySpinner = 2131296269;
			
			// aapt resource value: 0x7f090017
			public const int currencySpinner = 2131296279;
			
			// aapt resource value: 0x7f090011
			public const int dateFrom = 2131296273;
			
			// aapt resource value: 0x7f090013
			public const int dateTo = 2131296275;
			
			// aapt resource value: 0x7f090019
			public const int linearLayout1 = 2131296281;
			
			// aapt resource value: 0x7f090036
			public const int menu_edit = 2131296310;
			
			// aapt resource value: 0x7f090038
			public const int menu_preferences = 2131296312;
			
			// aapt resource value: 0x7f090037
			public const int menu_save = 2131296311;
			
			// aapt resource value: 0x7f090001
			public const int newBusinessTrip = 2131296257;
			
			// aapt resource value: 0x7f090004
			public const int newClothe = 2131296260;
			
			// aapt resource value: 0x7f090006
			public const int newSizeAmount = 2131296262;
			
			// aapt resource value: 0x7f090028
			public const int pieceCodeCnSpinner = 2131296296;
			
			// aapt resource value: 0x7f09002a
			public const int pieceColorNameSpinner = 2131296298;
			
			// aapt resource value: 0x7f09001f
			public const int pieceColorSpinner = 2131296287;
			
			// aapt resource value: 0x7f090020
			public const int pieceComponentSpinner = 2131296288;
			
			// aapt resource value: 0x7f090021
			public const int pieceCountryOfOriginSpinner = 2131296289;
			
			// aapt resource value: 0x7f09001e
			public const int pieceGroupSpinner = 2131296286;
			
			// aapt resource value: 0x7f09001d
			public const int pieceMainCategorySpinner = 2131296285;
			
			// aapt resource value: 0x7f09002c
			public const int pieceRowImage = 2131296300;
			
			// aapt resource value: 0x7f09002d
			public const int pieceRowName = 2131296301;
			
			// aapt resource value: 0x7f090029
			public const int pieceSetSpinner = 2131296297;
			
			// aapt resource value: 0x7f090024
			public const int pieceSizeAmountText = 2131296292;
			
			// aapt resource value: 0x7f090023
			public const int pieceSupplierSpinner = 2131296291;
			
			// aapt resource value: 0x7f09001c
			public const int pieceTopCategorySpinner = 2131296284;
			
			// aapt resource value: 0x7f090018
			public const int saveNewBusinessTrip = 2131296280;
			
			// aapt resource value: 0x7f090032
			public const int saveNewSizeAmount = 2131296306;
			
			// aapt resource value: 0x7f09002b
			public const int savePieceButton = 2131296299;
			
			// aapt resource value: 0x7f090015
			public const int seasonSpinner = 2131296277;
			
			// aapt resource value: 0x7f090005
			public const int showClothesListView = 2131296261;
			
			// aapt resource value: 0x7f090031
			public const int sizeAmountAmountEditText = 2131296305;
			
			// aapt resource value: 0x7f090030
			public const int sizeAmountAmountText = 2131296304;
			
			// aapt resource value: 0x7f090007
			public const int sizeAmountListView = 2131296263;
			
			// aapt resource value: 0x7f090034
			public const int sizeAmountRowAmount = 2131296308;
			
			// aapt resource value: 0x7f090035
			public const int sizeAmountRowSaveButton = 2131296309;
			
			// aapt resource value: 0x7f090033
			public const int sizeAmountRowSizeName = 2131296307;
			
			// aapt resource value: 0x7f09002f
			public const int sizeAmountSizeSpinner = 2131296303;
			
			// aapt resource value: 0x7f09002e
			public const int sizeAmountSizeText = 2131296302;
			
			// aapt resource value: 0x7f09000c
			public const int textView1 = 2131296268;
			
			// aapt resource value: 0x7f09000e
			public const int textView2 = 2131296270;
			
			// aapt resource value: 0x7f090010
			public const int textView3 = 2131296272;
			
			// aapt resource value: 0x7f090012
			public const int textView4 = 2131296274;
			
			// aapt resource value: 0x7f090014
			public const int textView5 = 2131296276;
			
			// aapt resource value: 0x7f090016
			public const int textView6 = 2131296278;
			
			// aapt resource value: 0x7f090000
			public const int toolbar = 2131296256;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f040000
			public const int AllBusinessTrip = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int AllPiece = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int AllSizeAmount = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int BusinessTripRow = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int NewBusinessTrip = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int Piece = 2130968581;
			
			// aapt resource value: 0x7f040006
			public const int PieceRow = 2130968582;
			
			// aapt resource value: 0x7f040007
			public const int SizeAmount = 2130968583;
			
			// aapt resource value: 0x7f040008
			public const int SizeAmountRow = 2130968584;
			
			// aapt resource value: 0x7f040009
			public const int toolbar = 2130968585;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f080000
			public const int top_menus = 2131230720;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f030000
			public const int ic_action_content_create = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int ic_action_content_save = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int ic_menu_copy_holo_dark = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int ic_menu_cut_holo_dark = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int ic_menu_paste_holo_dark = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int ic_menu_search_holo_dark = 2130903045;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f060000
			public const int app_name = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int openCamera = 2131099649;
			
			// aapt resource value: 0x7f060002
			public const int openPiece = 2131099650;
			
			// aapt resource value: 0x7f060003
			public const int planet_prompt = 2131099651;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f070002
			public const int CiuchAppSplash = 2131165186;
			
			// aapt resource value: 0x7f070001
			public const int CiuchAppTheme = 2131165185;
			
			// aapt resource value: 0x7f070000
			public const int CiuchAppThemeBase = 2131165184;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
