#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("CiuchApp.Mobile.Resource", IsApplication=true)]

namespace CiuchApp.Mobile
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f060000
			public const int planets_array = 2131099648;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f040003
			public const int colorAccent = 2130968579;
			
			// aapt resource value: 0x7f040001
			public const int colorPrimary = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int colorPrimaryDark = 2130968578;
			
			// aapt resource value: 0x7f040000
			public const int launcher_background = 2130968576;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int answear = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070001
			public const int CityTextView = 2131165185;
			
			// aapt resource value: 0x7f070014
			public const int ClotheDestription = 2131165204;
			
			// aapt resource value: 0x7f070012
			public const int ClotheImage = 2131165202;
			
			// aapt resource value: 0x7f070013
			public const int ClotheName = 2131165203;
			
			// aapt resource value: 0x7f070017
			public const int ClotheNumberOfSizeL = 2131165207;
			
			// aapt resource value: 0x7f070016
			public const int ClotheNumberOfSizeM = 2131165206;
			
			// aapt resource value: 0x7f070015
			public const int ClotheNumberOfSizeS = 2131165205;
			
			// aapt resource value: 0x7f070000
			public const int CountryTextView = 2131165184;
			
			// aapt resource value: 0x7f070002
			public const int DatesTextView = 2131165186;
			
			// aapt resource value: 0x7f07001c
			public const int businessTripTextInfo = 2131165212;
			
			// aapt resource value: 0x7f07001b
			public const int businessTripsListView = 2131165211;
			
			// aapt resource value: 0x7f070007
			public const int citySpinner = 2131165191;
			
			// aapt resource value: 0x7f070018
			public const int clotheRowImage = 2131165208;
			
			// aapt resource value: 0x7f070019
			public const int clotheRowName = 2131165209;
			
			// aapt resource value: 0x7f070005
			public const int countrySpinner = 2131165189;
			
			// aapt resource value: 0x7f07000f
			public const int currencySpinner = 2131165199;
			
			// aapt resource value: 0x7f070009
			public const int dateFrom = 2131165193;
			
			// aapt resource value: 0x7f07000b
			public const int dateTo = 2131165195;
			
			// aapt resource value: 0x7f070003
			public const int gridLayout1 = 2131165187;
			
			// aapt resource value: 0x7f070011
			public const int linearLayout1 = 2131165201;
			
			// aapt resource value: 0x7f07001a
			public const int newBusinessTrip = 2131165210;
			
			// aapt resource value: 0x7f07001d
			public const int newClothe = 2131165213;
			
			// aapt resource value: 0x7f070010
			public const int saveNewBusinessTrip = 2131165200;
			
			// aapt resource value: 0x7f07000d
			public const int seasonSpinner = 2131165197;
			
			// aapt resource value: 0x7f07001e
			public const int showClothesListView = 2131165214;
			
			// aapt resource value: 0x7f070004
			public const int textView1 = 2131165188;
			
			// aapt resource value: 0x7f070006
			public const int textView2 = 2131165190;
			
			// aapt resource value: 0x7f070008
			public const int textView3 = 2131165192;
			
			// aapt resource value: 0x7f07000a
			public const int textView4 = 2131165194;
			
			// aapt resource value: 0x7f07000c
			public const int textView5 = 2131165196;
			
			// aapt resource value: 0x7f07000e
			public const int textView6 = 2131165198;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int BusinessTripRow = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int NewBusinessTrip = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Piece = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int PieceRow = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int SelectBusinessTrip = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int SelectPiece = 2130903045;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050000
			public const int app_name = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int openCamera = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int openPiece = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int planet_prompt = 2131034115;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
