#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("CiuchApp.Mobile.Resource", IsApplication=true)]

namespace CiuchApp.Mobile
{
	
	
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7F010000
			public const int Binding = 2130771968;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7F020000
			public const int colorAccent = 2130837504;
			
			// aapt resource value: 0x7F020001
			public const int colorPrimary = 2130837505;
			
			// aapt resource value: 0x7F020002
			public const int colorPrimaryDark = 2130837506;
			
			// aapt resource value: 0x7F020003
			public const int colorWhiteText = 2130837507;
			
			// aapt resource value: 0x7F020004
			public const int launcher_background = 2130837508;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7F030000
			public const int logo = 2130903040;
			
			// aapt resource value: 0x7F030001
			public const int splash = 2130903041;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7F04000F
			public const int backSizeAmount = 2130968591;
			
			// aapt resource value: 0x7F040010
			public const int businessTripsListView = 2130968592;
			
			// aapt resource value: 0x7F040011
			public const int citySpinner = 2130968593;
			
			// aapt resource value: 0x7F040000
			public const int CityTextView = 2130968576;
			
			// aapt resource value: 0x7F040012
			public const int countrySpinner = 2130968594;
			
			// aapt resource value: 0x7F040001
			public const int CountryTextView = 2130968577;
			
			// aapt resource value: 0x7F040013
			public const int currencySpinner = 2130968595;
			
			// aapt resource value: 0x7F040014
			public const int dateFrom = 2130968596;
			
			// aapt resource value: 0x7F040002
			public const int DatesTextView = 2130968578;
			
			// aapt resource value: 0x7F040015
			public const int dateTo = 2130968597;
			
			// aapt resource value: 0x7F040003
			public const int Description = 2130968579;
			
			// aapt resource value: 0x7F040016
			public const int linearLayout1 = 2130968598;
			
			// aapt resource value: 0x7F040004
			public const int ListView = 2130968580;
			
			// aapt resource value: 0x7F040017
			public const int menu_edit = 2130968599;
			
			// aapt resource value: 0x7F040018
			public const int menu_new = 2130968600;
			
			// aapt resource value: 0x7F040019
			public const int menu_save = 2130968601;
			
			// aapt resource value: 0x7F04001A
			public const int menu_syncImages = 2130968602;
			
			// aapt resource value: 0x7F04001B
			public const int newSizeAmount = 2130968603;
			
			// aapt resource value: 0x7F040005
			public const int PieceBuyPriceText = 2130968581;
			
			// aapt resource value: 0x7F04001C
			public const int pieceCodeCnSpinner = 2130968604;
			
			// aapt resource value: 0x7F04001D
			public const int pieceColorNameSpinner = 2130968605;
			
			// aapt resource value: 0x7F04001E
			public const int pieceColorSpinner = 2130968606;
			
			// aapt resource value: 0x7F04001F
			public const int pieceComponentSpinner = 2130968607;
			
			// aapt resource value: 0x7F040020
			public const int pieceCountryOfOriginSpinner = 2130968608;
			
			// aapt resource value: 0x7F040006
			public const int PieceEstimatedDateOfShipmentDate = 2130968582;
			
			// aapt resource value: 0x7F040007
			public const int PieceEstimatedTimeOfDeliveryDate = 2130968583;
			
			// aapt resource value: 0x7F040021
			public const int pieceGroupSpinner = 2130968609;
			
			// aapt resource value: 0x7F040008
			public const int PieceImage = 2130968584;
			
			// aapt resource value: 0x7F040022
			public const int pieceMainCategorySpinner = 2130968610;
			
			// aapt resource value: 0x7F040009
			public const int PieceNameText = 2130968585;
			
			// aapt resource value: 0x7F04000A
			public const int PieceOrderDate = 2130968586;
			
			// aapt resource value: 0x7F040023
			public const int pieceRowImage = 2130968611;
			
			// aapt resource value: 0x7F040024
			public const int pieceRowName = 2130968612;
			
			// aapt resource value: 0x7F040025
			public const int pieceSetSpinner = 2130968613;
			
			// aapt resource value: 0x7F040026
			public const int pieceSizeAmountText = 2130968614;
			
			// aapt resource value: 0x7F040027
			public const int pieceSupplierSpinner = 2130968615;
			
			// aapt resource value: 0x7F040028
			public const int pieceTopCategorySpinner = 2130968616;
			
			// aapt resource value: 0x7F040029
			public const int saveNewSizeAmount = 2130968617;
			
			// aapt resource value: 0x7F04002A
			public const int savePieceButton = 2130968618;
			
			// aapt resource value: 0x7F04002B
			public const int seasonSpinner = 2130968619;
			
			// aapt resource value: 0x7F04002C
			public const int showClothesListView = 2130968620;
			
			// aapt resource value: 0x7F04002D
			public const int sizeAmountAmountEditText = 2130968621;
			
			// aapt resource value: 0x7F04002E
			public const int sizeAmountAmountText = 2130968622;
			
			// aapt resource value: 0x7F04002F
			public const int sizeAmountListView = 2130968623;
			
			// aapt resource value: 0x7F040030
			public const int sizeAmountRowAmount = 2130968624;
			
			// aapt resource value: 0x7F040031
			public const int sizeAmountRowSaveButton = 2130968625;
			
			// aapt resource value: 0x7F040032
			public const int sizeAmountRowSizeName = 2130968626;
			
			// aapt resource value: 0x7F040033
			public const int sizeAmountSizeSpinner = 2130968627;
			
			// aapt resource value: 0x7F040034
			public const int sizeAmountSizeText = 2130968628;
			
			// aapt resource value: 0x7F04000B
			public const int Spinner1 = 2130968587;
			
			// aapt resource value: 0x7F04000C
			public const int TextForId = 2130968588;
			
			// aapt resource value: 0x7F04000D
			public const int TextForName = 2130968589;
			
			// aapt resource value: 0x7F040035
			public const int textView1 = 2130968629;
			
			// aapt resource value: 0x7F040036
			public const int textView2 = 2130968630;
			
			// aapt resource value: 0x7F040037
			public const int textView3 = 2130968631;
			
			// aapt resource value: 0x7F040038
			public const int textView4 = 2130968632;
			
			// aapt resource value: 0x7F040039
			public const int textView5 = 2130968633;
			
			// aapt resource value: 0x7F04003A
			public const int textView6 = 2130968634;
			
			// aapt resource value: 0x7F04000E
			public const int Title = 2130968590;
			
			// aapt resource value: 0x7F04003B
			public const int toolbar = 2130968635;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7F050000
			public const int AllBusinessTrip = 2131034112;
			
			// aapt resource value: 0x7F050001
			public const int AllPiece = 2131034113;
			
			// aapt resource value: 0x7F050002
			public const int AllSizeAmount = 2131034114;
			
			// aapt resource value: 0x7F050003
			public const int BindedBusinessTrip = 2131034115;
			
			// aapt resource value: 0x7F050004
			public const int BindedListItemRow = 2131034116;
			
			// aapt resource value: 0x7F050005
			public const int BusinessTripRow = 2131034117;
			
			// aapt resource value: 0x7F050006
			public const int ListItemRow = 2131034118;
			
			// aapt resource value: 0x7F050007
			public const int NewBusinessTrip = 2131034119;
			
			// aapt resource value: 0x7F050008
			public const int Piece = 2131034120;
			
			// aapt resource value: 0x7F050009
			public const int PieceRow = 2131034121;
			
			// aapt resource value: 0x7F05000A
			public const int SizeAmount = 2131034122;
			
			// aapt resource value: 0x7F05000B
			public const int SizeAmountRow = 2131034123;
			
			// aapt resource value: 0x7F05000C
			public const int toolbar = 2131034124;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7F060000
			public const int top_menus = 2131099648;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7F070000
			public const int ic_action_content_create = 2131165184;
			
			// aapt resource value: 0x7F070001
			public const int ic_action_content_new = 2131165185;
			
			// aapt resource value: 0x7F070002
			public const int ic_action_content_save = 2131165186;
			
			// aapt resource value: 0x7F070003
			public const int ic_action_content_save_new = 2131165187;
			
			// aapt resource value: 0x7F070004
			public const int ic_menu_copy_holo_dark = 2131165188;
			
			// aapt resource value: 0x7F070005
			public const int ic_menu_cut_holo_dark = 2131165189;
			
			// aapt resource value: 0x7F070006
			public const int ic_menu_paste_holo_dark = 2131165190;
			
			// aapt resource value: 0x7F070007
			public const int ic_menu_search_holo_dark = 2131165191;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7F080001
			public const int app_name = 2131230721;
			
			// aapt resource value: 0x7F080000
			public const int Hello = 2131230720;
			
			// aapt resource value: 0x7F080002
			public const int openCamera = 2131230722;
			
			// aapt resource value: 0x7F080003
			public const int openPiece = 2131230723;
			
			// aapt resource value: 0x7F080004
			public const int planet_prompt = 2131230724;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7F090000
			public const int CiuchAppSplash = 2131296256;
			
			// aapt resource value: 0x7F090001
			public const int CiuchAppTheme = 2131296257;
			
			// aapt resource value: 0x7F090002
			public const int CiuchAppThemeBase = 2131296258;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			// aapt resource value: { 0x7F010000 }
			public static int[] BindingExpression = new int[] {
					2130771968};
			
			// aapt resource value: 0
			public const int BindingExpression_Binding = 0;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
